### Register a new user
POST http://127.0.0.1:8000/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "Student",
    "fullname":"student_firstname student_lastname",
    "email": "student@student.example.com",
    "password": "1234",
    "role": "student",
    "faculty": "Engineering",
    "major": "Computer Science",
    "yearleveltutor": "2",
    "yearlevelstudent": "1",
    "courses": "COMP 123"
} 
### Login a user
POST http://127.0.0.1:8000/login/ HTTP/1.1
Content-Type: application/json

{
    "username_or_email": "Tutor",
    "password": "1234"
}

### get all tutors
GET http://127.0.0.1:8000/get-all-tutors/ HTTP/1.1
Content-Type: application/json

### get all students
GET http://127.0.0.1:8000/get-all-students/ HTTP/1.1
Content-Type: application/json

###
POST http://127.0.0.1:8000/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzc2OTQ4LCJpYXQiOjE3NDEyNDA5NDgsImp0aSI6ImE3OGQ0ZjNmYmY0ZDRjZjlhNTExODc5ZTJmYTUwNDEyIiwidXNlcl9pZCI6M30.Co84YbQGnLdKmAKII57s9M5BLGurTp50EzVONABALyM

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Mjc3Njk0OCwiaWF0IjoxNzQxMjQwOTQ4LCJqdGkiOiJiYWM1NWM5MWM5MDc0NTdjODk1YWE0NzFmNGFhNjZkZSIsInVzZXJfaWQiOjN9.nLBl3AA1p6rMzp0Tp0aoZ-c83DxnkYzA3648DBqp04Q",
}

#------------------------------------- _Student_ -----------------------------------
### Search tutors
GET http://127.0.0.1:8000/search-tutors/?tutorname=&faculty=&major=&course= HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0

### Search tutors
GET http://127.0.0.1:8000/search-tutors/?all=true HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0

### Request a session with a tutor
POST http://127.0.0.1:8000/request-session/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0

{
    "tutor": 2,
    "session_type": "one-on-one",
    "requested_time": "2023-10-15T14:00:00Z",
    "message": "I have problem with calculus"
}

### Make a payment
POST http://127.0.0.1:8000/make-payment/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0

{
    "scheduled_session": 1,
    "amount": "50.00",
    "platform_fee": "5.00",
    "transaction_id": "txn_1234567890"
}


### Send a message
POST http://127.0.0.1:8000/send-message/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0

{
    "receiver": 2,
    "content": "Hi, can we schedule a session tomorrow?"
}

### Get messages
GET http://127.0.0.1:8000/get-messages/?query=all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0
### Get messages
GET http://127.0.0.1:8000/get-messages/?query=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0


### Leave feedback for a tutor
POST http://127.0.0.1:8000/leave-feedback/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0

{  
    "to_user": 2,
    "rating": 5,
    "comment": "Great session, very helpful!"
}

### Get notifications
GET http://127.0.0.1:8000/get-notifications/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0

### Browse tutors for a specific course (GET)
GET http://127.0.0.1:8000/browse-tutors/?course_id=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1MjQxLCJpYXQiOjE3NDEyNDkyNDEsImp0aSI6ImQyZTVhMDg4YmZjNzQ4NWE5YzRjZTI1ZTEzODI3MmFiIiwidXNlcl9pZCI6Nn0.G8J0_NK_eJmZFxHGS9TZ08RwSaODZ7whzNXIBWgG4u0

#------------------------------------------ _Tutor_ -----------------------------------------

### Tutor pending session listings
GET http://127.0.0.1:8000/request-session-listings/?query=pending HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1Mjg4LCJpYXQiOjE3NDEyNDkyODgsImp0aSI6ImM4ZmJjNzhiMTk4ZDRiZjBiMjBiNDRhMGU5NTgwOWFiIiwidXNlcl9pZCI6NX0.vS6brk8rVzbQKNemZOtj_MOEnkYXprh8TWLSG7G9Wto

### Tutor accepted session listings
GET http://127.0.0.1:8000/request-session-listings/?query=accepted HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1Mjg4LCJpYXQiOjE3NDEyNDkyODgsImp0aSI6ImM4ZmJjNzhiMTk4ZDRiZjBiMjBiNDRhMGU5NTgwOWFiIiwidXNlcl9pZCI6NX0.vS6brk8rVzbQKNemZOtj_MOEnkYXprh8TWLSG7G9Wto

### Request a session with a tutor
POST http://127.0.0.1:8000/request-session-listings/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1Mjg4LCJpYXQiOjE3NDEyNDkyODgsImp0aSI6ImM4ZmJjNzhiMTk4ZDRiZjBiMjBiNDRhMGU5NTgwOWFiIiwidXNlcl9pZCI6NX0.vS6brk8rVzbQKNemZOtj_MOEnkYXprh8TWLSG7G9Wto

{
    "request_session_id": 2
}

### Send a message
POST http://127.0.0.1:8000/send-message/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1Mjg4LCJpYXQiOjE3NDEyNDkyODgsImp0aSI6ImM4ZmJjNzhiMTk4ZDRiZjBiMjBiNDRhMGU5NTgwOWFiIiwidXNlcl9pZCI6NX0.vS6brk8rVzbQKNemZOtj_MOEnkYXprh8TWLSG7G9Wto

{
    "receiver": 2,
    "content": "Hi, can we schedule a session tomorrow?"
}


### Get messages
GET http://127.0.0.1:8000/get-messages/?query=all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1Mjg4LCJpYXQiOjE3NDEyNDkyODgsImp0aSI6ImM4ZmJjNzhiMTk4ZDRiZjBiMjBiNDRhMGU5NTgwOWFiIiwidXNlcl9pZCI6NX0.vS6brk8rVzbQKNemZOtj_MOEnkYXprh8TWLSG7G9Wto

### Get messages
GET http://127.0.0.1:8000/get-messages/?query=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzg1Mjg4LCJpYXQiOjE3NDEyNDkyODgsImp0aSI6ImM4ZmJjNzhiMTk4ZDRiZjBiMjBiNDRhMGU5NTgwOWFiIiwidXNlcl9pZCI6NX0.vS6brk8rVzbQKNemZOtj_MOEnkYXprh8TWLSG7G9Wto


