### Register a new user
POST https://accentor490.pythonanywhere.com/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "student",
    "fullname":"student_firstname student_lastname",
    "email": "student@student.example.com",
    "password": "1234",
    "role": "student",
    "faculty": "Engineering",
    "major": "Computer Science",
    "yearleveltutor": "2",
    "yearlevelstudent": "1",
    "courses": "COMP 123"
}  
### Login a user - Login and Get profile - Profile
POST https://accentor490.pythonanywhere.com/login/ HTTP/1.1
Content-Type: application/json
 
{
    "username_or_email": "student",
    "password": "1234"
}

### get all tutors
GET https://accentor490.pythonanywhere.com/get-all-tutors/ HTTP/1.1
Content-Type: application/json

### get all students
GET https://accentor490.pythonanywhere.com/get-all-students/ HTTP/1.1
Content-Type: application/json

###
POST https://accentor490.pythonanywhere.com/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzc2OTQ4LCJpYXQiOjE3NDEyNDA5NDgsImp0aSI6ImE3OGQ0ZjNmYmY0ZDRjZjlhNTExODc5ZTJmYTUwNDEyIiwidXNlcl9pZCI6M30.Co84YbQGnLdKmAKII57s9M5BLGurTp50EzVONABALyM

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Mjc3Njk0OCwiaWF0IjoxNzQxMjQwOTQ4LCJqdGkiOiJiYWM1NWM5MWM5MDc0NTdjODk1YWE0NzFmNGFhNjZkZSIsInVzZXJfaWQiOjN9.nLBl3AA1p6rMzp0Tp0aoZ-c83DxnkYzA3648DBqp04Q",
}

#------------------------------------- _Student_ -----------------------------------
### Dashboard
GET https://accentor490.pythonanywhere.com/dashboard/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

### Search tutors - Find tutor
GET https://accentor490.pythonanywhere.com/search-tutors/?tutorname=&faculty=&major=&course= HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

### Search tutors - Find tutor
GET https://accentor490.pythonanywhere.com/search-tutors/?all=true HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

### Request a session with a tutor - Find Tutor
POST https://accentor490.pythonanywhere.com/request-session/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

{
    "tutor": 1,
    "session_type": "one-on-one",
    "requested_time": "2025-10-15T14:00:00Z",
    "message": "I have problem with calculus"
}

### Tutor pending session listings - Requests
GET https://accentor490.pythonanywhere.com/request-session-listings/?query=all HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

### Request a session with a tutor - My sessions
GET https://accentor490.pythonanywhere.com/request-session-listings/?query=search&id=5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk


### Send a message Messages
POST https://accentor490.pythonanywhere.com/send-message/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

{
    "session_request_id": 3,
    "content": "sure. I will be available."
}

### Get messages -Messages
GET https://accentor490.pythonanywhere.com/get-messages/?query=all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

### Get messages _ Messages
GET https://accentor490.pythonanywhere.com/get-messages/?query=3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk


### Get transactions
GET https://accentor490.pythonanywhere.com/get-transactions/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

### Make a payment
POST https://accentor490.pythonanywhere.com/make-payment/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

{
    "amount": "50.00",
    "platform_fee": "5.00"
}


### Get Recordings
GET https://accentor490.pythonanywhere.com/recording/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

### Leave feedback for a tutor
POST https://accentor490.pythonanywhere.com/leave-feedback/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

{  
    "to_user": 2,
    "rating": 5,
    "comment": "Great session, very helpful!"
}

### Get notifications
GET https://accentor490.pythonanywhere.com/get-notifications/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk

### Get video
GET https://accentor490.pythonanywhere.com/video/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2NjUxLCJpYXQiOjE3NDEzNjA2NTEsImp0aSI6ImU0ZDVlY2Y3ODYzYjQ4ZjZiYmYyNjc5OTc2ZjRjYzJmIiwidXNlcl9pZCI6Mn0.zTeYDNImKfa6EcF2uLbrLCzYBzX2dI_XAS7vtJSl8Sk


#------------------------------------------ _Tutor_ -----------------------------------------
### Get Dashboard - dashboard
GET https://accentor490.pythonanywhere.com/dashboard/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

### Tutor pending session listings - Requests
GET https://accentor490.pythonanywhere.com/request-session-listings/?query=pending HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

### Tutor accepted session listings - My sessions
GET https://accentor490.pythonanywhere.com/request-session-listings/?query=accepted HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

### Request a session with a tutor - My sessions
GET https://accentor490.pythonanywhere.com/request-session-listings/?query=search&id=5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE


### Request a session with a tutor - My sessions <accept session>
POST https://accentor490.pythonanywhere.com/accept-decline-session/1/?action=accept HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

### Request a session with a tutor - My sessions <decline session>
POST https://accentor490.pythonanywhere.com/accept-decline-session/2/?action=decline HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

{
    "decline_reason": "I am a little held up"
}

### Send a message - messages
POST https://accentor490.pythonanywhere.com/send-message/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

{
    "session_request_id": 3,
    "content": "Hi, we can have a meeting tommorow"
}

### Get messages -Messages
GET https://accentor490.pythonanywhere.com/get-messages/?query=all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

### Get messages - Messages
GET https://accentor490.pythonanywhere.com/get-messages/?query=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

### Get earnings - Earnings
GET https://accentor490.pythonanywhere.com/get-transactions/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

### Withdraw - withdrawal
POST https://accentor490.pythonanywhere.com/withdrawal/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

{
    "amount": 50
}


### Recordings - upload
POST https://accentor490.pythonanywhere.com/recording/?query=upload HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

{
    "title": "Calculus Basics - Part 1",
    "course": "MATH101",
    "price": 15.00,
    "description": "Introducing basics to calculus 1,2 and 3",
    "file_url":"fileurl"
}

### Recordings - list recordings
GET https://accentor490.pythonanywhere.com/recording/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODk2MzgwLCJpYXQiOjE3NDEzNjAzODAsImp0aSI6Ijc0MTFjZmMzNjdmYjQzMmI4MWViZWVkMzRkNmI0OGRmIiwidXNlcl9pZCI6MX0.jmMk4cxRFEsBwUYNRfYM7cBZx1qjSTDO4S6LiqwWSjE

