# Generated by Django 5.1.6 on 2025-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
