# Generated by Django 5.1.6 on 2025-02-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tutorprofile_course_tutorprofile_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.major'),
        ),
    ]
