# Generated by Django 5.1.6 on 2025-03-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payment_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='course',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
