# Generated by Django 5.1.6 on 2025-03-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_receiver_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read_status',
            new_name='read_status_student',
        ),
        migrations.AddField(
            model_name='message',
            name='read_status_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
