# Generated by Django 5.1.6 on 2025-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recording_cost_alter_recording_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
    ]
