# Generated by Django 5.1.6 on 2025-02-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tutorprofile_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='faculty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='major',
            field=models.TextField(blank=True, null=True),
        ),
    ]
