# Generated by Django 5.1.6 on 2025-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studentprofile_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='session_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
