# Generated by Django 5.1.6 on 2025-02-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='year_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
