# Generated by Django 5.1.6 on 2025-02-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tutorprofile_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
