# Generated by Django 5.1.6 on 2025-02-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sessionrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.TextField(blank=True, null=True),
        ),
    ]
